import { InferGetServerSidePropsType, GetServerSideProps } from 'next';
import Head from 'next/head';

import { styled } from '@stitches/react';
import { Navigation } from '@/components/Navigation';
import { InterfaceViewer } from '@/components/InterfaceViewer';

type PageName = string;

export const getServerSideProps: GetServerSideProps<{ pageName: PageName }> = async () => {
  return {
    props: {
      pageName: 'page - 2',
    },
  };
};

const Main = styled('main', {
  padding: '8px',
  backgroundColor: '#F1F2F6',
});

const PageTwo = ({ pageName }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>NX - Webview Interface Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>{pageName}</h1>
        <Navigation />
        <InterfaceViewer />
      </Main>
    </>
  );
};

export default PageTwo;
